BOOTLOADER = atmel-dfu
LTO_ENABLE = yes


ENCODER_ENABLE = yes
COMBO_ENABLE = yes
SWAP_HANDS_ENABLE = yes
DEBOUNCE_TYPE = sym_eager_pr
SPLIT_KEYBOARD = yes

TAP_DANCE_ENABLE = yes
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
SLEEP_LED_ENABLE = no
MIDI_ENABLE = no
UNICODEMAP_ENABLE = no
UCIS_ENABLE = no
CAPS_WORD_ENABLE = yes
